services:
  chromium:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "6080:6080" # noVNC web access
      - "9222:9222" # Chrome remote debugging
    environment:
      - DISPLAY_NUM=1
      - WIDTH=1280
      - HEIGHT=800
      # Uncomment to persist Chrome user data
      # - CHROME_USER_DATA_DIR=/data/chrome
    # Uncomment to persist Chrome user data
    # volumes:
    #   - ./data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "supervisorctl", "status", "all"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
