# fly.toml app configuration file generated for chrome-template on 2025-05-08T01:19:20+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chrome-template'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 6080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
