# fly.toml app configuration file generated for chrome-template on 2025-05-08T01:19:20+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chrome-template'
primary_region = 'sjc'

[build]

[[services]]
internal_port = 6080
processes = ["app"]
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "2s"
interval = "5s"
timeout = "2s"

[[services]]
internal_port = 9222
processes = ["app"]
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
port = 9222
force_https = true
handlers = ["http"]

[[services.ports]]
handlers = ["tls", "http"]
port = 9223

[[services.tcp_checks]]
grace_period = "3s"
interval = "5s"
timeout = "2s"

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 1
